#!/bin/csh -fx

grep -q sdkconfig CONFIG_IDF_TARGET_ESP32=y
if(! $status) echo "-S1"
grep -q sdkconfig CONFIG_IDF_TARGET_ESP32S2=y
if(! $status) echo "-S2"
grep -q sdkconfig CONFIG_IDF_TARGET_ESP32S3=y
if(! $status) echo "-S3"
grep -q sdkconfig CONFIG_IDF_TARGET_ESPC3=y
if(! $status) echo "-C3"
grep -q sdkconfig CONFIG_IDF_TARGET_ESPH2=y
if(! $status) echo "-H2"

grep -q sdkconfig CONFIG_FREERTOS_UNICORE=y
if(!status) echo "-solo"
